### ISSUE TITLE
Why do block-compressed textures have to be aligned to a multiple of the texel block size?

### ISSUE THREAD

**Issue by magcius** [gpuweb/gpuweb#2006]
The spec says this:

> Textures in block-based compressed GPUTextureFormats always have a mipmap level 0 whose [[descriptor]].size is a multiple of the texel block size, but the lower mipmap levels might not be multiples of the texel block size and can have paddings.

But this is not a restriction of any of the major APIs that are targets (D3D12, Metal, Vulkan), that I can find. It *is* a restriction in D3D11, but this restriction seems to have happened by accident. Because mipmaps can already not be texel-aligned, hardware basically needs to support this anyway.

My sleuthing has only lead me to https://github.com/gpuweb/gpuweb/pull/623 which added the text, and https://github.com/gpuweb/gpuweb/issues/363 which is the discussion that proposed the restriction, which references a D3D10 manual page.

I would propose dropping this text from the spec.

**Comment by Jiawei-Shao** [comment]
Hi @magcius,

I think that restriction is still needed for WebGPU on D3D12.

I did an experiment about creating a 127x127 BC1 texture on D3D12, and I got the following error message from D3D12 Debug Layer (GPU: Nvidia 2080Ti, driver: 27.21.14.6089, Windows 10 Version 10.0.19042.1110):

> D3D12 ERROR: ID3D12Device::CreateCommittedResource: Textures created with certain Formats must align the resource dimensions properly. D3D12_RESOURCE_DESC::Format is **BC1_UNORM**. D3D12_RESOURCE_DESC::Width is 127, and must be **a multiple of 4**. D3D12_RESOURCE_DESC::Height is 127, and must be **a multiple of 4**. [ STATE_CREATION ERROR #597: CREATERESOURCE_INVALIDDIMENSIONS]

The code I test is as below:
```
    ComPtr<ID3D12Resource> srcTexture;
    D3D12_RESOURCE_DESC textureDesc = {};
    textureDesc.MipLevels = 4;
    textureDesc.Format = DXGI_FORMAT_BC1_UNORM;
    textureDesc.Width = 127;
    textureDesc.Height = 127;
    textureDesc.Flags = D3D12_RESOURCE_FLAG_NONE;
    textureDesc.DepthOrArraySize = 1;
    textureDesc.SampleDesc.Count = 1;
    textureDesc.SampleDesc.Quality = 0;
    textureDesc.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;

    ThrowIfFailed(device->CreateCommittedResource(
        &CD3DX12_HEAP_PROPERTIES(D3D12_HEAP_TYPE_DEFAULT),
        D3D12_HEAP_FLAG_NONE,
        &textureDesc,
        D3D12_RESOURCE_STATE_COPY_DEST,
        nullptr,
        IID_PPV_ARGS(&srcTexture)));
```

**Comment by magcius** [comment]
I was told by MS that D3D12 no longer had this restriction, but I did not test it. I'll double-check to see if this is just a bug in the validation layer. Thanks for checking.

**Comment by Jiawei-Shao** [comment]
> I was told by MS that D3D12 no longer had this restriction.

@RafaelCintron Could you help us verify this?

**Comment by magcius** [comment]
It seems like it is fixed in the D3D12 Agility SDK. Whether this is just a bug in the validation layer or a deeper feature that requires driver support, I don't know yet.

**Comment by magcius** [comment]
There's now a feature flag for this: `D3D12_FEATURE_DATA_D3D12_OPTIONS8::UnalignedBlockTexturesSupported`

I have been told that every driver supports this already, you just have to use the Agility SDK.

**Comment by RafaelCintron** [comment]
> @RafaelCintron Could you help us verify this?

@magcius is correct.  With the Agility SDK and on Windows 11, UnalignedBlockTexturesSupported will be true.  

However, per the [Agility SDK Getting Started](https://devblogs.microsoft.com/directx/gettingstarted-dx12agility/#OS) page, the Agility SDK is only supported for Windows 10 versions 1909 and greater.  Previous versions of Windows will still have this limitation.  

Since people want to support WebGPU on all versions of Windows 10, we'll need to make this feature be a WebGPU extension.

**Comment by Kangz** [comment]
Maybe this limitation is something we could consider lifting in a future "flexibility" optional feature along with a bunch of other annoying constraints.

**Comment by magcius** [comment]
It would be nice to have this as an optional supported feature in WebGPU; wgpu might be considering adding an extension for this, as bevy users are running into this limitation, see https://github.com/gfx-rs/wgpu/issues/7677

**Comment by brendan-duncan** [comment]
Compressed texture alignment restrictions causes frequent issues with Unity WebGPU users, specifically for for mipmapped textures. Having the feature to enable unaligned textures would be very helpful.

**Comment by castano** [comment]
This feature would also be extremely useful for [spark.js](https://github.com/Ludicon/spark.js) users. It makes sense to observe this constraint when shipping pre-compressed textures for maximum compatibility. However, for textures that are compressed at runtime having to scale the texture to the aligned dimensions adds an additional source of error that would not need to be present for most users. spark.js could easily check whether the feature is available, and only perform the necessary scaling when it's not.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2026%E2%80%9006%E2%80%9024#why-do-block-compressed-textures-have-to-be-aligned-to-a-multiple-of-the-texel-block-size-2006">GPU Web WG 2026-06-24 Atlantic-time</a></summary>

  * CW: Some APIs require that textures be a multiple of the block size of their format. This is a bit weird, because the other mip levels won’t be full blocks anyway. There’s a feature bit in D3D12 for lifting this restriction, so we could advertise a WebGPU feature for lifting the WebGPU restriction.  
  * JB: Why this issue?  
  * CW: The most recent comment gives a bunch of feedback on compressed texture support in WebGPU. We figured if it was small we could pull it forward. The biggest piece of work here is writing the tests, that’s the most difficult part.  
  * JB: We need to be realistic about whether M2 is approaching or receding. But if this is small, then that might be fine.  
  * CW: We just need a champion to write the tests. Implementation should be very easy.  
  * KN: We previously considered whether there was a possible workaround: just not using level 0 of the native texture.  
  * CW: That sounds weird.  
  * KN: But it would let us include it in core.  
  * CW: I don’t think it would work, because you’d multiply the texture dimension by four.  
  * KN: There’d be fixups.  
  * JB: What about memory consumption?  
  * KN: Well, maybe there’s a feature that lets you have mip level zero not allocated.  
  * CW: This sounds really fishy.  
  * KN: Or, we could polyfill by rounding up and then correcting everywhere.  
  * JB: Sounds tricky, but possible  
  * CW: What about sampling at edges?  
  * CW: Let’s say this is waiting for someone to write the tests.  

</details>

**Comment by castano** [comment]
Thanks for discussing this feature and taking it into consideration. I'd be happy to volunteer to write the necessary tests. I've started work on that: https://github.com/gpuweb/cts/pull/4676 but I'll update this issue when I feel test coverage is complete.

**Comment by castano** [comment]
I've updated the testsuite to provide full coverage for the proposed feature and validate the scenarios that it enables - not just creation of block-compressed textures not aligned to the block dimensions, but also verifies that copies of partial blocks are supported and produce correct results.

Additionally I've proposed the corresponding changes to the spec: https://github.com/gpuweb/gpuweb/pull/6312

I do not have a W3C account, so I cannot link my GitHub account. What are the necessary steps to create one?

**Comment by Kangz** [comment]
https://www.w3.org/account/ is where you get an account. You may join the group through your company or as an invited expert depending, but for this feature specifically, because it is trivial in its text, I think it would be fine if you didn't join the WG either. @tidoust FYI

**Comment by kainino0x** [comment]
Fixed in #6312 + https://github.com/gpuweb/cts/pull/4676

Chromium bug for those interested https://crbug.com/528245806
